StockApp/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ServiceContracts;
using StockApp.Models;
using StockApp.ServiceContracts;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace StockApp.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly ILogger<StocksController> _logger;
        private readonly TradingOption _tradingoptions;

        public StocksController(IFinnhubService finnhubService, IOptions<TradingOption> tradingoptions,ILogger<StocksController> logger)
        {
            _finnhubService = finnhubService;
            _logger = logger;
            _tradingoptions = tradingoptions.Value;
        }
        [Route("/")]
        [Route("[action]/{stock?}")]
        [Route("~/[action]/{stock?}")]

        public async Task<IActionResult> Explore(string? stock, bool showAll = false)
        {
            _logger.LogInformation("In StockController Explore action Method");
            _logger.LogDebug("stock: {stock}, showAll: {showAll}",stock,showAll);
            // get company profile from API Server
            List<Dictionary<string, string>>? stocksDictionary = await _finnhubService.GetStocks();
            List<Stock> stocks = new List<Stock>();
            // filter the stocks
            if (stocksDictionary is not null)
            {
                if (!showAll && _tradingoptions.Top25PopularStocks != null)
                {
                    string[]? top25PopularStocksList = _tradingoptions.Top25PopularStocks.Split(',');
                    if (top25PopularStocksList is not null)
                    {
                        stocksDictionary = stocksDictionary.Where(temp => top25PopularStocksList.Contains(Convert.ToString(temp["symbol"]))).ToList();
                    }
                }
            }
            // convert dictionary object into Stock object
            stocks = stocksDictionary.Select(temp => new Stock()
            {
                StockName = Convert.ToString(temp["description"]),
                StockSymbol = Convert.ToString(temp["symbol"])
            }).ToList();
            ViewBag.stock = stock;
            return View(stocks);
        }
    }
}

StockApp/Controllers/TradeController.cs
using Entities.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ServiceContracts;
using StockApp.Filters.ActionFilters;
using StockApp.Models;
using StockApp.ServiceContracts;

namespace StockApp.Controllers
{
    [Route("[controller]")]
    public class TradeController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly IStockService _stockService;
        private readonly IConfiguration _configuration;
        private readonly ILogger<TradeController> _logger;
        private readonly TradingOption _tradingOptions;

        public TradeController(IFinnhubService finnhubService,IStockService stockService, IOptions<TradingOption> tradingOptions,IConfiguration configuration, ILogger<TradeController> logger)
        {
            _finnhubService = finnhubService;
            this._stockService = stockService;
            this._configuration = configuration;
            this._logger = logger;
            _tradingOptions = tradingOptions.Value;
        }
        [Route("[action]/{stockSymbol?}")]
        [Route("~/[controller]/{stockSymbol?}")]
        public async Task<IActionResult> Index(string StockSymbol)
        {
            _logger.LogInformation("In TradeController Index action method ");
            _logger.LogDebug("StockSymbol: {stockSymbol}",StockSymbol);
            if (string.IsNullOrEmpty(StockSymbol))
            {
                StockSymbol = "MSFT";
            }
            //Get company profile from API server 
            Dictionary<string, object> companyProfileDictionary = await _finnhubService.GetCompanyProfile(StockSymbol);
            //Get stock price quotes from API service
            Dictionary<string, object> stockQuoteDictionary = await _finnhubService.GetStockPriceQuote(StockSymbol);
            StockTrade stockTrade = new StockTrade
            {
                StockSymbol = StockSymbol
            };
            //load data from finnhubservice
            if (companyProfileDictionary!=null && stockQuoteDictionary != null)
            {
                stockTrade = new StockTrade() { StockSymbol= Convert.ToString(companyProfileDictionary["ticker"]),
                    StockName = Convert.ToString(companyProfileDictionary["name"]),
                    Price = Convert.ToDouble(stockQuoteDictionary["c"].ToString())
                };
            }
            ViewBag.FinnhubToken = _configuration["FinnhubToken"];
            return View(stockTrade);
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest buyOrderRequest)
        {
            ModelState.Clear();
            TryValidateModel(buyOrderRequest);
            if(!ModelState.IsValid)
            {
                ViewBag.Errors= ModelState.Values.SelectMany(v => v.Errors).Select(v=>v.ErrorMessage).ToList();
                StockTrade trade = new StockTrade()
                {
                    StockName=buyOrderRequest.StockName, Price=buyOrderRequest.Price,
                    StockSymbol=buyOrderRequest.StockSymbol
                };
                return View("Index", trade);
            }
            BuyOrderResponse buyOrderResponse = await _stockService.CreateBuyOrder(buyOrderRequest);
            return RedirectToAction(nameof(Order));
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(CreateOrderActionFilter))]
        public async Task<IActionResult> SellOrder(SellOrderRequest sellOrderRequest)
        {
            ModelState.Clear();
            TryValidateModel(sellOrderRequest);
            if (!ModelState.IsValid)
            {
                ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(v => v.ErrorMessage).ToList();
                StockTrade trade = new StockTrade()
                {
                    StockName = sellOrderRequest.StockName,
                    Price = sellOrderRequest.Price,
                    StockSymbol = sellOrderRequest.StockSymbol
                };
                return View("Index", trade);
            }
            SellOrderResponse sellOrderResponse = await _stockService.CreateSellOrder(sellOrderRequest);
            return RedirectToAction(nameof(Order));
        }

        [Route("[action]")]
        public async Task<IActionResult> Order()
        {
            Orders orders = new Orders()
            {
                BuyOrders= await _stockService.GetBuyOrders(),
                SellOrders=await _stockService.GetSellOrders(),
            };
            return View(orders);
        }
    }
}

StockApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title | Stocks</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <div class="container">
        <div class="page-content">
            <div class="margin-bottom">
                <div class="flex" id="top-bar-div">
                    <div class="flex-1" id="app-title-div">
                        <h1 class="app-title">
                            <i class="fa-solid fa-money-bill-trend-up"></i>
                            Stocks
                        </h1>
                    </div>

                    <div class="flex-1 pr" id="search-box-div">
                        <input type="search" class="search-text" placeholder="Search Stock" name="SearchText" />
                        <i class="fa-solid fa-gear"></i>
                    </div>
                    <div class="flex-0">
                        <div class="navbar account-links">
                            <ul>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li>
                                        <i class="fa-solid fa-user"></i>
                                        @User.Identity?.Name
                                    </li>
                                    @if(User.IsInRole("Admin"))
                                    {
                                        <li>
                                            <a asp-controller="Home" asp-area="Admin" asp-action="Index">Admin Home</a>
                                        </li>
                                    }
                                    
                                    <li>
                                        <a asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                }
                                else
                                {
                                    <li>
                                        <a asp-controller="Account" asp-action="Register">Register</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Account" asp-action="Login">Login</a>
                                    </li>
                                }
                            </ul>
                        </div>

                    </div>


                </div>

            </div>

            <div class="navbar mb">
                <ul>
                    @if (ViewBag.CurrentUrl == "~/Explore")
                    {
                        <li><a asp-controller="Stocks" asp-action="Explore" class="nav-active">Explore</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Stocks" asp-action="Explore">Explore</a></li>
                    }
                    @if (ViewBag.CurrentUrl == "~/Trade/Index")
                    {
                        <li><a asp-controller="Trade" asp-action="Index" class="nav-active">Trade</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Trade" asp-action="Index">Trade</a></li>
                    }
                    @if (ViewBag.CurrentUrl == "~/Trade/Order")
                    {
                        <li><a asp-controller="Trade" asp-action="Order" class="nav-active">Orders</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Trade" asp-action="Order">Orders</a></li>
                    }

                </ul>
            </div>

            @RenderBody()
        </div>

    </div>

    @await RenderSectionAsync("scripts", required: false)

</body>
</html>